version: "2"

plugins:
    phpcodesniffer:
        enabled: true
        config:
            standard: "PSR2"
        exclude_patterns:
            - /tests
            - /example.php
            - /docs
            - /vendor
