.php-unit-test:
  stage: test
  variables:
    COMPOSER_CACHE_DIR: "$CI_PROJECT_DIR/.composer"
  cache:
    paths:
      - .composer
  before_script:
    - mkdir -p .composer build/logs
    - composer install --no-interaction
  script:
    - vendor/bin/phpunit -c phpunit.xml --color=always

php56-unit-test:
  extends: .php-unit-test
  image: iras/php5-composer:1
  script:
    - vendor/bin/phpunit -c phpunit.xml --color=always --printer=PHPUnit_TextUI_ResultPrinter

php71-unit-test:
  extends: .php-unit-test
  image: iras/php7-composer:1
  before_script:
    - apk add --no-cache openssl
    - wget https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 -O ./cc-test-reporter
    - chmod +x ./cc-test-reporter
    - ./cc-test-reporter before-build
    - composer install --no-interaction
  script:
    - php -dzend_extension=xdebug.so vendor/bin/phpunit -c phpunit.xml --coverage-clover=clover.xml --coverage-text --color=always
  after_script:
    - test "$CI_JOB_STATUS" == "success" && TEST_RESULT=0 || TEST_RESULT=1
    - ./cc-test-reporter after-build --coverage-input-type clover --exit-code $TEST_RESULT

php72-unit-test:
  extends: .php-unit-test
  image: iras/php7-composer:2

php73-unit-test:
  extends: .php-unit-test
  image: iras/php7-composer:3

php74-unit-test:
  extends: .php-unit-test
  image: iras/php7-composer:4

php80-unit-test:
  extends: .php-unit-test
  image: iras/php8-composer:0
  before_script:
    - mkdir -p .composer build/logs
    - composer install --no-interaction --ignore-platform-reqs
