name: Generate and Deploy Documentation

on:
  push:
    branches:
      - master
      - f/new-reference

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate Reference Documentation
        run: docker run -v $GITHUB_WORKSPACE:/data iras/phpdoc:3.7.1-twig.extensions --template docs/_reference -c phpdoc.xml --force --visibility PUBLIC

      - name: Build Documentation Site
        run: docker run -v $GITHUB_WORKSPACE:/data -e JEKYLL_UID=$(id -u) -e JEKYLL_GID=$(id -g) jekyll/jekyll:4 jekyll build --source /data/docs --destination /data/_site

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './_site'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
